<?php if($block->canShowInFrontEnd()){ ?>
<style type="text/css">
    .slideshow{
        position:relative;
        height: 400px;
        overflow:hidden;
        margin: 0 auto;
        width: 700px;
        padding: 10px;
        box-shadow: 0 0 20px rgba(0,0,0,0.4);
    }
    .slideshow div {
        position:absolute;
        top:0px;;
        left:0;
        z-index:8;
        top: 10px;
        left: 10px;
        right: 10px;
        bottom: 10px;
    }
    .slideshow div img
    {
        width: 100%; /*The image slide show width*/
        height:380px; /*The image slide show height*/
    }
    .slideshow div.active {
        z-index:10;
    }
    .slideshow div.lastactive {
        z-index:9;
    }

</style>
<div class="slideshow">
<?php
    $sliderId = $this->getData('slider');
    $banners = $block->getBanners($sliderId);

    if($banners)
    {
        foreach ($banners as $banner)
        {
            if($banner['image'])
            {
                $image = $block->getBaseUrl().'pub/media/sliderwidget/'.$banner['image'];
?>
    <div><a href="<?php echo $banner['link'] ?>"><img src="<?php echo $image?>"/></a></div>
<?php }}} ?>

</div>
<script type="text/javascript">
    require(['jquery'], function($){
        $(document).ready(function()
        {
            initSlideShow();

        });

        function initSlideShow()
        {
            if($('div').find('slideshow-container'))
            {
                $('.slideshow-container').hide();
            }

            if($(".slideshow div").length > 1)
            {
                var transationTime = 5000;
                $(".slideshow div:first").addClass('active');
                setInterval(slideChangeImage, transationTime);
            }
        }

        function slideChangeImage()
        {
            var active = $(".slideshow div.active"); //Get the current active element.
            if(active.length == 0)
            {
                active = $(".slideshow div:last"); //If do not see the active element is the last image.
            }

            var next = active.next().length ? active.next() : $(".slideshow div:first"); //get the next element to do the transition
            active.addClass('lastactive');
            next.css({opacity:0.0}) //do the fade in fade out transition
                .addClass('active')
                .animate({opacity:1.0}, 1500, function()
                {
                    active.removeClass("active lastactive");
                });

        }
    });
</script>
<?php } ?>